### ISSUE TITLE
Ce bouton n'est pas fonctionnel

### ISSUE THREAD

**Issue by jonasmaumene** [oystparis/oyst-1click-magento2#13]
![image.png](https://images.zenhubusercontent.com/58c7c64051aa2c3057786513/36fa0390-7bb4-42fd-b6dd-8b91368eea8f)

**Comment by mbouchotoyst** [comment]
Ceci est du au bouton everywhere, et au paramétrage du bouton dans la merchant. En effet, dans Magento (1 & 2) et Prestashop, si le bouton n'est pas associé à un formulaire alors il sera non efficient. Il faut juste dans ce cas, supprimer le sélecteur qui permet d'afficher ce bouton.
